trigger:
- main

pool:
  vmImage: 'ubuntu-latest'  # You can choose the appropriate Linux image

jobs:
- job: RunPlaywright
  displayName: 'Run Playwright Test'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11.4'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install playwright==1.39.0
  - script: |
      export LT_USERNAME="ritamg"
      export LT_ACCESS_KEY="TK7DCf2rFcBJzT3IHz4kD47lThhsHckrlGtiGkYyetAcixtrj5"
      python playwright_sample.py
